### ISSUE TITLE
Certain repos fail silently

### ISSUE THREAD

**Issue by ddnexus** [gruntwork-io/fetch#86] opened 2021-01-30 08:36 UTC
Works with other repos but the following fails/freezes:
```
$ fetch --repo="https://github.com/Jannomag/Yaru-Colors" --ref="20.10.1" --source-path="/Themes" /tmp/yaru-themes
Downloading git reference "20.10.1" of https://github.com/Jannomag/Yaru-Colors ...
```
It fails also with --commit, --tag, --branch etc.
Is there any way to debug what is happening?

**Comment by brikis98** [comment] 2021-02-01 14:47
Are you able to `git clone` that repo locally?

**Comment by ddnexus** [comment] 2021-02-01 23:34
Yes of course. Did you try to clone it and to run the command? I suspect you would get to the same conclusion.

**Comment by brikis98** [comment] 2021-02-02 09:31
Ah, I didn't realize that was an open source repo I had access to! Most people use `fetch` with private repos.

I can indeed confirm the bug. Not sure of the cause, and am too buried at the moment to dig in. If anyone has time to look into this, PRs are welcome!

**Comment by ddnexus** [comment] 2021-02-02 09:48
Is there any flag or any other way to get a debugging feedback from fetch?

**Comment by brikis98** [comment] 2021-02-02 10:13
No, not currently. Better logging is something we'd like to add.

**Comment by raidancampbell** [comment] 2021-09-26 15:40
I'm unable to reproduce this, and several new tags were created shortly after this ticket was raised related to `--ref`.  I suspect this isn't an issue anymore

**Comment by tonerdo** [comment] 2022-01-14 23:49
@ddnexus I looked into reproducing this and was unable to. This seems have possibly been fixed by updates to fetch. Closing out this issue, feel free to reopen if you encounter it again.

**Closed by tonerdo** 2022-01-14 23:49 UTC
Labels: bug
